In [1]:
# pandas is sql table form datastructure
import pandas as pd
# numpy is a multidimentional array
import numpy as np

In [3]:
# 1. Object creation
# creating series
series = pd.Series([1,3,5,np.nan,6,8])
series

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [5]:
# creating datetime index using dataframe
dates = pd.date_range('20130101',periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [37]:
print(np.random.randn(6,4))
# creating data frame
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df)

df2 = pd.DataFrame({ 'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4,dtype='int32'),
                    'E' : pd.Categorical(["package","train","package","train"]),
                    'F' : 'foo' ,
                   'G':[1,2,3,4]})

[[-0.93256084  0.97653639  1.40024194  0.67480626]
 [ 2.18901487  0.1136703  -0.8690588  -1.31088336]
 [-1.29000436 -1.58685521  2.40688802  2.31206722]
 [ 1.83382313 -2.30091232  1.85126921  0.63071685]
 [ 0.95935383 -1.30669859  0.44168213 -1.08681797]
 [ 0.96601034 -0.17535878 -0.8506643  -0.41180449]]
                   A         B         C         D
2013-01-01 -0.385818 -0.932764  0.257685  0.418018
2013-01-02  2.357594  2.116428  2.091997 -1.236248
2013-01-03 -0.103918 -0.327425 -1.111789 -0.118698
2013-01-04  0.562206  1.271350  0.143159 -1.008937
2013-01-05  1.046036  0.671016 -0.131514 -2.013103
2013-01-06 -0.580686  0.463642 -0.642242 -0.072926


In [38]:
df2

A          B    C  D        E    F  G
0  1.0 2013-01-02  1.0  3  package  foo  1
1  1.0 2013-01-02  1.0  3    train  foo  2
2  1.0 2013-01-02  1.0  3  package  foo  3
3  1.0 2013-01-02  1.0  3    train  foo  4

In [39]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
G             int64
dtype: object

In [40]:
pd.Series(1,index=list(range(4)),dtype='float32')

0    1.0
1    1.0
2    1.0
3    1.0
dtype: float32

In [41]:
np.array([3] * 4,dtype='int32')

array([3, 3, 3, 3], dtype=int32)

In [42]:
pd.Categorical(["package","train","package","train"])

[package, train, package, train]
Categories (2, object): [package, train]

In [43]:
print(dir(df2))

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'T', '_AXIS_ALIASES', '_AXIS_IALIASES', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '_AXIS_SLICEMAP', '__abs__', '__add__', '__and__', '__array__', '__array_wrap__', '__bool__', '__bytes__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmod__', '__rmul__', '__ror__',

In [44]:
df2.head(1)

A          B    C  D        E    F  G
0  1.0 2013-01-02  1.0  3  package  foo  1

In [45]:
df2.tail(1)

A          B    C  D      E    F  G
3  1.0 2013-01-02  1.0  3  train  foo  4

In [46]:
df2.describe(include="all")

A                    B    C    D      E    F         G
count   4.0                    4  4.0  4.0      4    4  4.000000
unique  NaN                    1  NaN  NaN      2    1       NaN
top     NaN  2013-01-02 00:00:00  NaN  NaN  train  foo       NaN
freq    NaN                    4  NaN  NaN      2    4       NaN
first   NaN  2013-01-02 00:00:00  NaN  NaN    NaN  NaN       NaN
last    NaN  2013-01-02 00:00:00  NaN  NaN    NaN  NaN       NaN
mean    1.0                  NaN  1.0  3.0    NaN  NaN  2.500000
std     0.0                  NaN  0.0  0.0    NaN  NaN  1.290994
min     1.0                  NaN  1.0  3.0    NaN  NaN  1.000000
25%     1.0                  NaN  1.0  3.0    NaN  NaN  1.750000
50%     1.0                  NaN  1.0  3.0    NaN  NaN  2.500000
75%     1.0                  NaN  1.0  3.0    NaN  NaN  3.250000
max     1.0                  NaN  1.0  3.0    NaN  NaN  4.000000

In [77]:
# pandas is sql table form datastructure
import pandas as pd
# numpy is a multidimentional array
import numpy as np

# 1. Object creation
# creating series
series = pd.Series([1,3,5,np.nan,6,8])
#print(series)

# creating datetime index using dataframe
dates = pd.date_range('20130101',periods=6)
#print(dates)

#print(np.random.randn(6,4))
# creating data frame
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))


A         B         C         D
2013-01-01 -0.849509  0.025927 -1.351931  0.388157
2013-01-02 -1.902426  1.234953 -1.944670 -1.054043
2013-01-03  1.759641 -1.436956 -0.516635  1.348472
2013-01-04 -0.879363 -0.942771 -0.508474  0.415253
2013-01-05 -1.002320  0.733036  1.125630  0.480067
2013-01-06  0.374073 -1.304382  0.647354 -0.825000

In [96]:
df["date"]=df.index
df["label"]=["a","b","c","d","e","f"]
df["label_number"]=[1,2,3,4,5,6]
df

A         B         C         D       date label  \
2013-01-01 -0.849509  0.025927 -1.351931  0.388157 2013-01-01     a   
2013-01-02 -1.902426  1.234953 -1.944670 -1.054043 2013-01-02     b   
2013-01-03  1.759641 -1.436956 -0.516635  1.348472 2013-01-03     c   
2013-01-04 -0.879363 -0.942771 -0.508474  0.415253 2013-01-04     d   
2013-01-05 -1.002320  0.733036  1.125630  0.480067 2013-01-05     e   
2013-01-06  0.374073 -1.304382  0.647354 -0.825000 2013-01-06     f   

            label_number  
2013-01-01             1  
2013-01-02             2  
2013-01-03             3  
2013-01-04             4  
2013-01-05             5  
2013-01-06             6

In [120]:
# Selction by label
# selecing single column by giving column name
# list in python
print(list(df["A"].values))
# numpy array
print(df["A"].values)

[-0.8495087438472078, -1.9024256491476017, 1.7596413350928386, -0.8793632187704643, -1.0023198580381203, 0.3740725665241651]
[-0.84950874 -1.90242565  1.75964134 -0.87936322 -1.00231986  0.37407257]


In [118]:
# taking the particular element of the column by label
df.loc['2013-01-02',["A"]]

A   -1.90243
Name: 2013-01-02 00:00:00, dtype: object

In [119]:
df[(df["A"]== -1.9024256491476017)]

A         B        C         D       date label  \
2013-01-02 -1.902426  1.234953 -1.94467 -1.054043 2013-01-02     b   

            label_number  
2013-01-02             2

In [57]:
df = pd.DataFrame({"A":[1,2,3,4]})
df

A
0  1
1  2
2  3
3  4

In [66]:
df[df["A"]==4]

A
3  4

In [67]:
df[df["A"]==4].values

array([[4]])

In [68]:
df[df["A"]==4].index.values

array([3])

In [70]:
# matrix a11
df.at[0,"A"]


1

In [73]:
df.iat[0,0]

1

In [111]:
np.abs(1.90242565)

1.90242565

In [121]:
df2 = df.copy()

In [122]:
df2

A         B         C         D       date label  \
2013-01-01 -0.849509  0.025927 -1.351931  0.388157 2013-01-01     a   
2013-01-02 -1.902426  1.234953 -1.944670 -1.054043 2013-01-02     b   
2013-01-03  1.759641 -1.436956 -0.516635  1.348472 2013-01-03     c   
2013-01-04 -0.879363 -0.942771 -0.508474  0.415253 2013-01-04     d   
2013-01-05 -1.002320  0.733036  1.125630  0.480067 2013-01-05     e   
2013-01-06  0.374073 -1.304382  0.647354 -0.825000 2013-01-06     f   

            label_number  
2013-01-01             1  
2013-01-02             2  
2013-01-03             3  
2013-01-04             4  
2013-01-05             5  
2013-01-06             6

In [123]:
df

A         B         C         D       date label  \
2013-01-01 -0.849509  0.025927 -1.351931  0.388157 2013-01-01     a   
2013-01-02 -1.902426  1.234953 -1.944670 -1.054043 2013-01-02     b   
2013-01-03  1.759641 -1.436956 -0.516635  1.348472 2013-01-03     c   
2013-01-04 -0.879363 -0.942771 -0.508474  0.415253 2013-01-04     d   
2013-01-05 -1.002320  0.733036  1.125630  0.480067 2013-01-05     e   
2013-01-06  0.374073 -1.304382  0.647354 -0.825000 2013-01-06     f   

            label_number  
2013-01-01             1  
2013-01-02             2  
2013-01-03             3  
2013-01-04             4  
2013-01-05             5  
2013-01-06             6

In [124]:
df2["extra"] = "hi"
df2

A         B         C         D       date label  \
2013-01-01 -0.849509  0.025927 -1.351931  0.388157 2013-01-01     a   
2013-01-02 -1.902426  1.234953 -1.944670 -1.054043 2013-01-02     b   
2013-01-03  1.759641 -1.436956 -0.516635  1.348472 2013-01-03     c   
2013-01-04 -0.879363 -0.942771 -0.508474  0.415253 2013-01-04     d   
2013-01-05 -1.002320  0.733036  1.125630  0.480067 2013-01-05     e   
2013-01-06  0.374073 -1.304382  0.647354 -0.825000 2013-01-06     f   

            label_number extra  
2013-01-01             1    hi  
2013-01-02             2    hi  
2013-01-03             3    hi  
2013-01-04             4    hi  
2013-01-05             5    hi  
2013-01-06             6    hi

In [125]:
df

A         B         C         D       date label  \
2013-01-01 -0.849509  0.025927 -1.351931  0.388157 2013-01-01     a   
2013-01-02 -1.902426  1.234953 -1.944670 -1.054043 2013-01-02     b   
2013-01-03  1.759641 -1.436956 -0.516635  1.348472 2013-01-03     c   
2013-01-04 -0.879363 -0.942771 -0.508474  0.415253 2013-01-04     d   
2013-01-05 -1.002320  0.733036  1.125630  0.480067 2013-01-05     e   
2013-01-06  0.374073 -1.304382  0.647354 -0.825000 2013-01-06     f   

            label_number  
2013-01-01             1  
2013-01-02             2  
2013-01-03             3  
2013-01-04             4  
2013-01-05             5  
2013-01-06             6

In [127]:
df2=df
df2

A         B         C         D       date label  \
2013-01-01 -0.849509  0.025927 -1.351931  0.388157 2013-01-01     a   
2013-01-02 -1.902426  1.234953 -1.944670 -1.054043 2013-01-02     b   
2013-01-03  1.759641 -1.436956 -0.516635  1.348472 2013-01-03     c   
2013-01-04 -0.879363 -0.942771 -0.508474  0.415253 2013-01-04     d   
2013-01-05 -1.002320  0.733036  1.125630  0.480067 2013-01-05     e   
2013-01-06  0.374073 -1.304382  0.647354 -0.825000 2013-01-06     f   

            label_number  
2013-01-01             1  
2013-01-02             2  
2013-01-03             3  
2013-01-04             4  
2013-01-05             5  
2013-01-06             6

In [129]:
df2["extra1"] ="Hi"
df2

A         B         C         D       date label  \
2013-01-01 -0.849509  0.025927 -1.351931  0.388157 2013-01-01     a   
2013-01-02 -1.902426  1.234953 -1.944670 -1.054043 2013-01-02     b   
2013-01-03  1.759641 -1.436956 -0.516635  1.348472 2013-01-03     c   
2013-01-04 -0.879363 -0.942771 -0.508474  0.415253 2013-01-04     d   
2013-01-05 -1.002320  0.733036  1.125630  0.480067 2013-01-05     e   
2013-01-06  0.374073 -1.304382  0.647354 -0.825000 2013-01-06     f   

            label_number extra1  
2013-01-01             1     Hi  
2013-01-02             2     Hi  
2013-01-03             3     Hi  
2013-01-04             4     Hi  
2013-01-05             5     Hi  
2013-01-06             6     Hi

In [130]:
df

A         B         C         D       date label  \
2013-01-01 -0.849509  0.025927 -1.351931  0.388157 2013-01-01     a   
2013-01-02 -1.902426  1.234953 -1.944670 -1.054043 2013-01-02     b   
2013-01-03  1.759641 -1.436956 -0.516635  1.348472 2013-01-03     c   
2013-01-04 -0.879363 -0.942771 -0.508474  0.415253 2013-01-04     d   
2013-01-05 -1.002320  0.733036  1.125630  0.480067 2013-01-05     e   
2013-01-06  0.374073 -1.304382  0.647354 -0.825000 2013-01-06     f   

            label_number extra1  
2013-01-01             1     Hi  
2013-01-02             2     Hi  
2013-01-03             3     Hi  
2013-01-04             4     Hi  
2013-01-05             5     Hi  
2013-01-06             6     Hi

In [131]:
# 1. Object creation
# creating series
series = pd.Series([1,3,5,np.nan,6,8])
#print(series)

# creating datetime index using dataframe
dates = pd.date_range('20130101',periods=6)
#print(dates)

#print(np.random.randn(6,4))
# creating data frame
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('20130102', periods=6))
df['F'] = s1
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])

df1.loc[dates[0]:dates[1],'E'] = 1

In [132]:
print(df1)
# To drop any rows that have missing data.
print(df1.dropna(how='any'))
# Filling missing data.
print(df1.fillna(value=5))
#To get the boolean mask where values are nan.
print(pd.isna(df1))

                   A         B         C         D    F    E
2013-01-01 -2.207591  0.169375 -0.833750  1.457847  NaN  1.0
2013-01-02 -0.387927 -2.148119 -0.078960 -0.470595  1.0  1.0
2013-01-03 -0.122418 -1.022228 -0.508223 -0.897742  2.0  NaN
2013-01-04  0.964250  0.356081  0.424563  0.914505  3.0  NaN
                   A         B        C         D    F    E
2013-01-02 -0.387927 -2.148119 -0.07896 -0.470595  1.0  1.0
                   A         B         C         D    F    E
2013-01-01 -2.207591  0.169375 -0.833750  1.457847  5.0  1.0
2013-01-02 -0.387927 -2.148119 -0.078960 -0.470595  1.0  1.0
2013-01-03 -0.122418 -1.022228 -0.508223 -0.897742  2.0  5.0
2013-01-04  0.964250  0.356081  0.424563  0.914505  3.0  5.0
                A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True
